name: Data Collection and Push

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collection
        env:
          FREEPIK_COOKIES: ${{ secrets.FREEPIK_COOKIES }}
          OPENART_COOKIES: ${{ secrets.OPENART_COOKIES }}
          PIXLR_COOKIES: ${{ secrets.PIXLR_COOKIES }}
          CONSIDER_MAX_ITERATON: ${{ secrets.CONSIDER_MAX_ITERATON }}
          MAX_ITERATON: ${{ secrets.MAX_ITERATON }}
          WATING: ${{ secrets.WATING }}
          TRY_MANY: ${{ secrets.TRY_MANY }}
          SEARCH_PROMPTS: ${{ secrets.SEARCH_PROMPTS }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add -f collected
          git commit -m "Collected and updated data: $(date)"
          git push
